Add MMORoomGroup component
youngmonkeys/game-box pull request #10
Opened 2021-08-06 12:40 UTC by vu-luong

2021-08-06 12:42 UTC, vu-luong commented
@tvd12 Anh ơi, mình nên test những method nào nhỉ? Anh chỉ cần viết ra tên method thôi ạ, logic để em tự nghĩ xem sao. Có quy tắc nào để biết mình cần test những gì không anh?

2021-08-06 13:23 UTC, tvd12 commented
@vu-luong test hết em ạ, nguyên tắc của mình là test nhầm còn hơn bỏ sót, :)

2021-08-06 13:25 UTC, tvd12 requested changes

2021-08-06 13:25 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
em cần override hàm này ở cả lớp `SynchronizedRoomManager` em ạ
À vậy thì ở cái PR trước, mình cũng quên chưa update lớp `SynchronizedPlayerManager` em ạ, em bổ sung luôn nhé

2021-08-06 13:29 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
`SynchronizedRoomManager` extends `AbstractPlayerManager` anh ạ, `SynchronizedPlayerManager` cũng extends `AbstractPlayerManager`. Vậy chỉ chỉ cần override ở lớp Abstract Manager là được chứ nhỉ?

2021-08-06 13:31 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
synchronize nó phải thế này em ạ: 

```java
@Override
	public void getRoomList(List<R> buffer) {
		synchronized (synchronizedLock) {
			super.getRoomList(buffer);	
		}
	}
```

2021-08-06 13:33 UTC, vu-luong commented
> @vu-luong test hết em ạ, nguyên tắc của mình là test nhầm còn hơn bỏ sót, :)

Test hết cụ thể là sao anh nhỉ? Test chức năng, test not null của tất cả fields và methods hả anh?

2021-08-06 13:35 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
Quyền read mà vẫn cần lock hả anh, em tưởng chỉ cần lock khi write là đủ?

2021-08-06 13:37 UTC, tvd12 commented
> > @vu-luong test hết em ạ, nguyên tắc của mình là test nhầm còn hơn bỏ sót, :)
> 
> Test hết cụ thể là sao anh nhỉ? Test chức năng, test not null của tất cả fields và methods hả anh?

@vu-luong em  mở file `game-box/target/site/jacoco/index.html` em mở file report lên ví dụ của anh là `file:///Users/tvd12/Documents/tvd12/java/projects/game-box/target/site/jacoco/com.tvd12.gamebox.manager/MMORoomGroup.java.html#L79` em sẽ cần test để nó 80% được cover (màu xanh) nhé

2021-08-06 13:44 UTC, vu-luong commented
> > > @vu-luong test hết em ạ, nguyên tắc của mình là test nhầm còn hơn bỏ sót, :)
> > 
> > 
> > Test hết cụ thể là sao anh nhỉ? Test chức năng, test not null của tất cả fields và methods hả anh?
> 
> @vu-luong em mở file `game-box/target/site/jacoco/index.html` em mở file report lên ví dụ của anh là `file:///Users/tvd12/Documents/tvd12/java/projects/game-box/target/site/jacoco/com.tvd12.gamebox.manager/MMORoomGroup.java.html#L79` em sẽ cần test để nó 80% được cover (màu xanh) nhé

Cái này hay quá anh, hôm trước anh có nói mà giờ em mới hiểu 😄

2021-08-06 14:09 UTC, vu-luong commented
@tvd12  Làm sao test được roomGroup thoát thành công cái loop này vậy anh?

```java
	private void loop() {
		this.active = true;
		while (active) {
			try {
				this.updateRooms();
				Thread.sleep(timeTickMillis);
			} catch (Exception e) {
				logger.error("Room group loop error: ", e);
			}
		}
	}
```

2021-08-07 00:27 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
> Khi read mà vẫn cần lock hả anh, em tưởng chỉ cần lock khi write là đủ?

@tvd12 Anh giải thích cho em chỗ này với ạ

2021-08-07 01:14 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
@vu-luong đối với 1 biến primitive thì không cần em ạ, tuy nhiên List, Map hay các collection nói chung đề wrap 1 cái array ở bên trong, thế nên nó dẫn đến tình trạng là khi 1 phần tử bị xoá khỏi collection thì cái mảng nó cũng bị thay đổi theo, thành ra nếu cùng 1 thời điểm mà cùng đọc cùng ghi hay cùng xoá 1 phần tử ở vị trí thứ `index` thì nó sẽ gây ra tình trạng tranh chấp tài nguyên, nên người viết các thư viện Java họ đã xử lý bằng cách ném ra [ConcurrentModificationException](https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html) em ạ

2021-08-07 01:16 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
@vu-luong em có muốn bổ sung luôn trong PR này ko em? hay sẽ tách ra 1 PR khác?

2021-08-07 01:17 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/manager/AbstractRoomManager.java
> +		buffer.addAll(roomsByName.values());
Để em commit sửa luôn anh ạ

2021-08-07 01:44 UTC, tvd12 approved these changes

2021-08-07 01:44 UTC, merged