Add MMORoom
youngmonkeys/game-box pull request #4
Opened 2021-08-04 14:53 UTC by vu-luong

2021-08-04 15:52 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +		List<MMOPlayer> playerList = playerManager.getPlayerList();
Hàm này sẽ tạo bản copy mỗi lần gọi, vậy nên mình cần bổ sung hàm playerManager.getPlayers(List buffer) em ạ:

```java
/**
	 * Get player list to buffer
	 * 
	 * @param buffer the buffer
	 */
	void getPlayerList(List<P> buffer);
```

2021-08-04 16:19 UTC, tvd12 requested changes
PTAL

2021-08-04 16:19 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
hôm nọ anh review sót, nó phải thế này em ạ:

```java
package com.tvd12.gamebox.entity;

import com.tvd12.gamebox.math.Vec3;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@Getter
public class MMOPlayer extends Player {
	
	@Setter
	protected Vec3 position;
	
	@Setter
	protected Vec3 rotation;
	
	@Getter(AccessLevel.NONE)
	protected final Map<String, MMOPlayer> nearbyPlayers = new ConcurrentHashMap<>();
	
	public MMOPlayer(String name) {
		super(name);
	}
	
	protected MMOPlayer(Builder builder) {
		super(builder);
	}
	
	public void addNearbyPlayer(MMOPlayer otherPlayer) {
		this.nearbyPlayers.put(otherPlayer.getName(), otherPlayer);
	}
	
	public void removeNearByPlayer(MMOPlayer otherPlayer) {
		this.nearbyPlayers.remove(otherPlayer.getName());
	}
	
	/**
	 * To be used after onRoomUpdated to sync neighbor's positions for current player
	 *
	 * @param buffer initialized only once to maintain performance
	 */
	public void getNearbyPlayerNames(List<String> buffer) {
		buffer.addAll(nearbyPlayers.keySet());
	}
	
	public static Builder builder() {
		return new Builder();
	}
	
	public static class Builder extends Player.Builder<Builder> { // lớp này là lớp cuối, không có lớp nào cần thừa kế nữa nên mình chỉ cần để builder bình thường là được em ạ
		
		@Override
		protected Player newProduct() {
			return new MMOPlayer(this);
		}
		
		@Override
		public MMOPlayer build() {
			return (MMOPlayer) super.build();
		}
	}
}
```

2021-08-04 16:19 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +		List<MMOPlayer> playerList = playerManager.getPlayerList();
Nó sẽ kiểu thế này em ạ:

```java
package com.tvd12.gamebox.entity;

import java.util.ArrayList;
import java.util.List;

import com.tvd12.gamebox.manager.PlayerManager;
import com.tvd12.gamebox.manager.SynchronizedPlayerManager;

@SuppressWarnings("unchecked")
public class MMORoom extends NormalRoom {

	protected final List<MMOPlayer> playersBuffer;
	protected final List<MMORoomUpdateFinishedHandler> updateFinishedHandlers;
	protected final double distanceOfInterest;
	
	public MMORoom(Builder builder) {
		super(builder);
		this.playersBuffer = new ArrayList<>();
		this.updateFinishedHandlers = builder.updateFinishedHandlers;
		this.distanceOfInterest = builder.distanceOfInterest;
	}
	
	public void update() {
		playersBuffer.clear();
		playerManager.getPlayerList(playersBuffer);
		
		for (MMOPlayer player : playersBuffer) {
			for (MMOPlayer other : playersBuffer) {
				if (other != player) {
					double distance = player.getPosition().distance(other.getPosition());
					if (distance <= this.distanceOfInterest) {
						player.addNearbyPlayer(other);
					} else {
						player.removeNearByPlayer(other);
					}
				}
			}
		}
		
		notifyUpdateFinishedHandlers();
	}
	
	private void notifyUpdateFinishedHandlers() {
		for (MMORoomUpdateFinishedHandler handler : updateFinishedHandlers) {
			handler.onRoomUpdated(this);
		}
	}
	
	public static Builder builder() {
		return new Builder();
	}
	
	public static class Builder extends NormalRoom.Builder<Builder> {
		protected double distanceOfInterest;
		protected final List<MMORoomUpdateFinishedHandler> updateFinishedHandlers;
		
		public Builder() {
			this.updateFinishedHandlers = new ArrayList<>();
		}
		
		public Builder addRoomUpdateFinishedHandler(MMORoomUpdateFinishedHandler handler) {
			this.updateFinishedHandlers.add(handler);
			return this;
		}
		
		public Builder distanceOfInterest(double distance) {
			this.distanceOfInterest = distance;
			return this;
		}
		
		@Override
		public Builder defaultPlayerManager(int maxPlayer) {
			this.playerManager = new SynchronizedPlayerManager<>(maxPlayer);
			return this;
		}
		
		@SuppressWarnings("rawtypes")
		@Override
		public Builder playerManager(PlayerManager playerManager) {
			if(playerManager instanceof SynchronizedPlayerManager)
				return super.playerManager(playerManager);
			throw new IllegalArgumentException("playerManager must be SynchronizedPlayerManager");
		}
		
		@Override
		protected void preBuild() {
			if(playerManager == null)
				playerManager = new SynchronizedPlayerManager<>();
			super.preBuild();
		}
		
		@Override
		public MMORoom build() {
			return (MMORoom) super.build();
		}
		
		@Override
		protected MMORoom newProduct() {
			return new MMORoom(this);
		}
	}
}
```

2021-08-04 16:19 UTC, tvd12 commented on src/test/java/com/tvd12/gamebox/testing/MMORoomTest.java
> +		player1.getNearbyPlayerNames(buffer1);
nên là thế này em ạ:

```java
List<String> expectedNearbyPlayerNames1 = 
    ((Map<String, MMOPlayer>)FieldUtil.getFieldValue(player1, "nearbyPlayers"))
    .keySet()
    .stream()
    .collect(Collectors.toList());
Asserts.assertEquals(buffer1, expectedNearbyPlayerNames1);
```
Em update cho cả những cái khác nữa nhé

2021-08-04 16:19 UTC, tvd12 commented on src/test/java/com/tvd12/gamebox/testing/MMORoomTest.java
> +	public class A implements MMORoomUpdateFinishedHandler {
Em nên dùng mockito và dùng hàm verify em nhé

2021-08-04 16:19 UTC, tvd12 commented on src/test/java/com/tvd12/gamebox/testing/MMORoomTest.java
> +				.defaultPlayerManager(5)
chỗ này không cần thiết em ạ vì mình đã tạo default nếu không set em ạ

2021-08-04 16:19 UTC, tvd12 commented on src/test/java/com/tvd12/gamebox/testing/MMORoomTest.java
> +				.distanceOfInterest(100.0D)
Mình nên sử dụng hàm RandomUtil.randomInt em ạ

2021-08-04 16:19 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoomUpdateFinishedHandler.java
> +public interface MMORoomUpdateFinishedHandler {
anh nghĩ lại để là `MMORoomUpdatedHandler` có khi ngắn gọn mà vẫn đủ hiểu em nhỉ?

2021-08-05 00:35 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +		List<MMOPlayer> playerList = playerManager.getPlayerList();
Sao 

> ```java
> getPlayerList
> ```

Sao gọi PlayerManager. getPlayerList() lại tạo copy anh nhỉ? Em nghĩ nó chỉ tạo reference thôi chứ.

2021-08-05 00:44 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Em thấy trong cùng 1 MMORoom, các `MMOPlayer` sẽ nằm cùng thread. Vì sao thằng `nearbyPlayers` phải là `ConcurrentHashMap` mà không phải `HashMap` vậy anh?

2021-08-05 00:47 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +		List<MMOPlayer> playerList = playerManager.getPlayerList();
Ừ, chỗ đó ý anh là nó có 2 trường hợp của việc getPlayerList, 1 là dev sẽ tự viết lớp PlayerManager sẽ return kiểu new ArrayList(playerList) để tạo bản copy, cái này sẽ làm cho mỗi lần room update lại tạo ra 1 bản copy gây tốn bộ nhớ và giảm hiệu năng
Còn nếu trong trường hợp mình lấy reference như hiện tại, mà mình ko synchronize cái playerList kia đc, nó sẽ bị vấn đề đa luồng em ạ, vì ngoài room các luồng khác gọi từ socket cũng dùng chung player manager em ạ

2021-08-05 00:49 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Anh cẩn thận hơn thôi em ạ, phòng ông dev dùng lung tung :)

2021-08-05 00:51 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Em có thể dùng HashMap nếu em thấy hợp lý hơn nhé

2021-08-05 00:57 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
@tvd12 Theo như trên thì các thread từ socket cũng có thể gọi `addNearbyPlayer` và `removeNearByPlayer ` phải không anh? Vậy mình vẫn phải dùng `ConcurrentHashMap`.

2021-08-05 01:05 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Chỉ room mới đc gọi remoNearByPlayer thôi em ạ, nhưng cũng có thể dev sẽ mắc sai lầm, vậy mình cũng nên để ConcurrentHashMap em nhỉ

2021-08-05 01:07 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Có cách nào chỉ cho room gọi `removeNearByPlayer` khi code không anh nhỉ, không cho các thằng khác gọi?

2021-08-05 01:11 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Có em ạ, em bỏ public hàm đó để chỉ các lớp cùng gói mới access đc em nhé https://www.javatpoint.com/access-modifiers

2021-08-05 01:29 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Bỏ public thì lúc viết test làm sao gọi đến nó vậy anh?

2021-08-05 01:33 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Em phải gọi thông qua hàm update theo cơ chế position em nhé

2021-08-05 01:39 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
@tvd12 ý em là hàm addNearbyPlayersTest cho thằng MMOPlayer anh ạ, mình phải viết lại thằng này

2021-08-05 01:43 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Ở //given em gọi hàm update 1 lần để cho có player nearby, sau đó em set lại position, tiếp theo ở // when em gọi lần nữa em ạ

2021-08-05 01:52 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Nhưng mình đang test cho thằng MMOPlayer, update là của MMORoom rồi anh?

2021-08-05 01:55 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
À, em dùng thằng này nhé: https://github.com/tvd12/test-util/blob/master/src/main/java/com/tvd12/test/reflect/MethodInvoker.java

2021-08-05 01:56 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> -import java.util.stream.Collectors;
Anh đã add dependency sẵn rồi nhé

2021-08-05 02:49 UTC, vu-luong commented
@tvd12 Anh check commit mới nhé

2021-08-05 03:12 UTC, vu-luong commented
Ok anh, em fix rồi nhé

2021-08-05 03:12 UTC, tvd12 approved these changes
LGTM

2021-08-05 03:12 UTC, merged