Add SyncPositionRoomUpdatedHandler
youngmonkeys/game-box pull request #6
Opened 2021-08-05 15:12 UTC by vu-luong

@tvd12 Em đang vướng chỗ viết test cho thằng `SyncPositionRoomUpdatedHandler`. Làm sao mock được cái `responseFactory` vậy anh?

2021-08-05 16:48 UTC, tvd12 requested changes
PLTAL

2021-08-05 16:48 UTC, tvd12 commented on pom.xml
> +            <version>1.1.9</version>
nó sẽ kiểu thế này:

```xml
<properties>
  <ezy.server.version>1.1.9</ezy.server.version>
</properties>

<dependencies>
  <dependency>
    <groupId>com.tvd12</groupId>
    <artifactId>ezyfox-server-core</artifactId>
    <version>${ezy.server.version}</version>
  </dependency>
  <dependency>
      <groupId>com.tvd12</groupId>
      <artifactId>ezyfox-server-support</artifactId>
      <version>${ezy.server.version}</version>
      <optional>true</optional>
  </dependency>
</dependencies>
```

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/constant/Commands.java
> +public class Commands {
Các lớp constant đều phải khai báo là `public final class` để không cho phép thừa kế em ạ, nó sẽ giúp các IDE bỏ qua lớp này giúp cho cho các IDE nhẹ nhàng hơn, đồng thời em cũng phải tạo hàm tạo private để ngăn dev new đối tượng từ đây và giúp IDE em ạ

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/constant/Commands.java
> +	public static final String SYNC_POSITION = "sync_position";
command `SYNC_POSITION` mình sẽ sử dung UDP, nên cần tối thiểu gói tin em ạ, tổng kết lại là:

```java
package com.tvd12.gamebox.constant;

public final class Commands {
	
	private Commands() {}
	
	public static final String SYNC_POSITION = "s";
}
```

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> +import java.util.concurrent.atomic.AtomicBoolean;
thừa `import lombok.Setter;` em ạ

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMOPlayer.java
> +	public boolean getStateChanged() {
Các hàm boolean nên để là `is` em ạ, vậy nên là `isStateChanged()` em ạ

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +import com.tvd12.gamebox.handler.MMORoomUpdateHandler;
chỗ hàm `playerManager` thiếu `@SuppressWarnings("rawtypes")` em bổ sung nhé

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +	private static final float eps = 1e-8f;
private static final mình cần để tên biến là static em ạ, em có thể tham khảo java naming convention [ở đây](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) nhé

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +	private static final float eps = 1e-8f;
Thêm vào nữa là con số kia em đặt là viết tắt và giá trị mang tính khoa học quá em ạ, liệu có cách nào đặt tên biến được đầy đủ và con số dễ hiểu ko em? Hoặc không em có thể bổ sung comment để dev dễ hiểu hơn em ạ

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +		synchronized (room) {
chỗ này là không cần thiết và không có tác dụng em ạ, vì bản thân thằng playerManager nó đã là một đối tượng `synchronize` rồi em ạ, nghĩa là nó đã là thread safe rồi, em ko cần sync room nữa nhé

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +			Vec3 newRotation = player.getRotation();
get ra sau khi check để tăng thêm chút hiệu năng em nhé

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +public class SyncPositionRoomUpdatedHandler implements MMORoomUpdateHandler {
Lớp cha là `MMORoomUpdateHandler` thì lớp con không nên có thê chữ `d` em ạ, nên là `SyncPositionRoomUpdateHandler`

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +	private static final float eps = 1e-8f;
hình như biến này cũng thừa em ạ

2021-08-05 16:48 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/handler/SyncPositionRoomUpdatedHandler.java
> +				responseFactory.newObjectResponse()
command này sẽ dùng udp nên mình cần dùng array để tối thiểu data (bỏ được các key) em ạ, chung quy lớp này sẽ kiểu:

```java
package com.tvd12.gamebox.handler;

import java.util.ArrayList;
import java.util.List;

import com.tvd12.ezyfox.bean.annotation.EzyAutoBind;
import com.tvd12.ezyfoxserver.support.factory.EzyResponseFactory;
import com.tvd12.gamebox.constant.Commands;
import com.tvd12.gamebox.entity.MMOPlayer;
import com.tvd12.gamebox.entity.MMORoom;
import com.tvd12.gamebox.manager.PlayerManager;
import com.tvd12.gamebox.util.Vec3s;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
public class SyncPositionRoomUpdateHandler implements MMORoomUpdateHandler {
	
	@Setter
	@EzyAutoBind
	private EzyResponseFactory responseFactory;
	
	private final List<String> nearbyPlayerNamesBuffer = new ArrayList<>();
	
	@Override
	public void onRoomUpdated(MMORoom room) {
		PlayerManager<MMOPlayer> playerManager = room.getPlayerManager();

		for (MMOPlayer player : playerManager.getPlayerList()) {
			
			// Check if player's position or rotation is updated
			if (player.getStateChanged()) {
				player.setStateChanged(false);
				
				nearbyPlayerNamesBuffer.clear();
				player.getNearbyPlayerNames(nearbyPlayerNamesBuffer);

				responseFactory.newArrayResponse()
						.udpTransport()
						.command(Commands.SYNC_POSITION)
						.param(player.getName())
						.param(Vec3s.toArray(player.getPosition()))
						.param(Vec3s.toArray(player.getRotation()))
						.usernames(nearbyPlayerNamesBuffer)
						.execute();
			}
		}
	}
}
```

2021-08-05 16:48 UTC, tvd12 commented on src/test/java/com/tvd12/gamebox/testing/SyncPositionRoomUpdatedHandlerTest.java
> +public class SyncPositionRoomUpdatedHandlerTest {
lớp test cũng bỏ chữ `d` em nhé, nó sẽ kiểu này: 

```java
package com.tvd12.gamebox.testing;

import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.testng.annotations.Test;

import com.tvd12.ezyfoxserver.support.command.EzyArrayResponse;
import com.tvd12.ezyfoxserver.support.factory.EzyResponseFactory;
import com.tvd12.gamebox.constant.Commands;
import com.tvd12.gamebox.entity.MMOPlayer;
import com.tvd12.gamebox.entity.MMORoom;
import com.tvd12.gamebox.handler.SyncPositionRoomUpdatedHandler;
import com.tvd12.gamebox.math.Vec3;
import com.tvd12.gamebox.util.Vec3s;
import com.tvd12.test.reflect.FieldUtil;
import com.tvd12.test.util.RandomUtil;

public class SyncPositionRoomUpdateHandlerTest {
	
	@SuppressWarnings("unchecked")
	@Test
	public void casePlayerChangeStateTest() {
		// given
		String playerName = RandomUtil.randomShortAlphabetString();
		
		int nearByPlayerCount = RandomUtil.randomSmallInt();
		Set<String> nearByPlayerNames = RandomUtil.randomSet(nearByPlayerCount, String.class);
		List<String> nearByPlayerNameList = new ArrayList<>(nearByPlayerNames);
				
		Vec3 position = TestHelper.randomVec3();
		Vec3 rotation = TestHelper.randomVec3();
		
		EzyArrayResponse arrayResponse = mock(EzyArrayResponse.class);
		when(arrayResponse.udpTransport()).thenReturn(arrayResponse);
		when(arrayResponse.command(Commands.SYNC_POSITION)).thenReturn(arrayResponse);
		when(arrayResponse.param(playerName)).thenReturn(arrayResponse);
		when(arrayResponse.param(Vec3s.toArray(position))).thenReturn(arrayResponse);
		when(arrayResponse.param(Vec3s.toArray(rotation))).thenReturn(arrayResponse);
		when(arrayResponse.usernames(nearByPlayerNameList)).thenReturn(arrayResponse);
		doNothing().when(arrayResponse).execute();
		
		EzyResponseFactory responseFactory = mock(EzyResponseFactory.class);
		when(responseFactory.newArrayResponse()).thenReturn(arrayResponse);
		
		
		SyncPositionRoomUpdateHandler sut = new SyncPositionRoomUpdateHandler();
		sut.setResponseFactory(responseFactory);
		
		MMORoom room = MMORoom.builder()
				.name(RandomUtil.randomShortAlphabetString())
				.build();
		
		MMOPlayer player = new MMOPlayer(playerName);
		player.setPosition(position);
		player.setRotation(rotation);
		
		Map<String, MMOPlayer> nearbyPlayers = FieldUtil.getFieldValue(player, "nearbyPlayers");
		nearByPlayerNames.forEach(name -> {
			MMOPlayer nearByPlayer = new MMOPlayer(name);
			nearbyPlayers.put(name, nearByPlayer);
			room.getPlayerManager().addPlayer(nearByPlayer);
		});
		room.getPlayerManager().addPlayer(player);
		
		// when
		sut.onRoomUpdated(room);
		
		// then
		verify(responseFactory, times(1)).newArrayResponse();
		// tương tự với các hàm được when ở trên em nhé
	}
	
}
```

2021-08-06 01:35 UTC, vu-luong commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +import com.tvd12.gamebox.handler.MMORoomUpdateHandler;
Chỗ nào anh nhỉ? Em không thấy IDE cảnh báo

2021-08-06 01:43 UTC, tvd12 commented on src/main/java/com/tvd12/gamebox/entity/MMORoom.java
> +import com.tvd12.gamebox.handler.MMORoomUpdateHandler;
Chắc tại anh dùng eclipse, em tạm thời ko cần fix nhé

2021-08-06 02:56 UTC, vu-luong commented on src/test/java/com/tvd12/gamebox/testing/SyncPositionRoomUpdatedHandlerTest.java
> +public class SyncPositionRoomUpdatedHandlerTest {
```java
    verify(arrayResponse, times(1)).param(Vec3s.toArray(position));
    verify(arrayResponse, times(1)).param(Vec3s.toArray(rotation));
```

Chỗ này làm sao để verify nó không nhầm giữa 2 thằng này anh nhỉ?

2021-08-06 04:12 UTC, tvd12 approved these changes

2021-08-06 04:12 UTC, merged